apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: special-sa
spec:
  selector:
    matchLabels:
      special-rhpam: "true"
  resources:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: rhpam-scoped
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: rhpam-scoped
    rules:
    - apiGroups:
      - ""
      - apps
      - apps.openshift.io
      - rbac.authorization.k8s.io
      - route.openshift.io
      - build.openshift.io
      - image.openshift.io
      - app.kiegroup.org
      resources:
        - '*'
      verbs:
        - '*'
    - apiGroups:
      - monitoring.coreos.com
      resources:
      - servicemonitors
      verbs:
      - get
      - create
    - apiGroups:
      - operators.coreos.com
      resources:
      - subscriptions
      - clusterserviceversions
      verbs:
      - '*'
    - apiGroups:
      - apps
      resourceNames:
      - kie-cloud-operator
      resources:
      - deployments/finalizers
      verbs:
      - update
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: rhpam-scoped-bindings
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: rhpam-scoped
    subjects:
    - kind: ServiceAccount
      name: rhpam-scoped
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: rhpam-op-group
    spec:
      serviceAccountName: rhpam-scoped
      targetNamespaces:
      - mm-test1

