apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhpam-scoped-bindings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhpam-scoped
subjects:
- kind: ServiceAccount
  name: rhpam-scoped
