apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: businessautomation-operator
spec:
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: businessautomation-operator
  channel: stable
